target 'wheather app'
project '/Users/maki/Stuff/ios/wheather app/wheather app.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'FontAwesome.swift'
pod 'SVProgressHUD'
